### ISSUE TITLE
Make it easier to compile + test locally

### ISSUE THREAD

**Issue by clbarnes** [constantinpape/z5#67] opened 2018-06-27 14:55 UTC
- Makefile
- .gitignore for build-related files
- Instructions
- List system dependencies

**Comment by jakirkham** [comment] 2018-08-06 17:13
Given this has a mix of C++ and Python requirements, maybe [`conda`'s `environment.yml`]( https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file ) would work?

**Comment by constantinpape** [comment] 2018-08-07 16:48
I have added two requirement files (`requirements36.yml` and `requirements27.yml`) to set up
conda development environments for python2/3 and updated the Readme accordingly:
https://github.com/constantinpape/z5#from-source

@clbarnes 
I don't really see the value in providing a Makefile.
It will be much harder to compose than the CMake project and will not be cross-platform capable by design.
The instructions should still be improved though....

**Comment by constantinpape** [comment] 2018-08-16 21:28
@clbarnes 
I have updated and tested the instructions to install from source
and we have requirement files for python 2.7 and 3.6 now.

Let me know if you think we could do anything else to improve this issue, otherwise I would close it.

**Closed** 2018-10-15 08:53 UTC

**Comment by perlman** [comment] 2018-10-19 14:41
pip (PyPI) would be fantastic too...

**Comment by constantinpape** [comment] 2018-10-19 14:51
@perlman I had a look into putting the package on pip, at some point, but I didn't get around to put in the c++ dependencies (boost, xtensor-python, compression libraries).
FWIW, the branch with my attempts at a pip build is still there:
https://github.com/constantinpape/z5/tree/pip

**Comment by jakirkham** [comment] 2018-10-29 18:05
FWIW we did some preliminary experiments in [conda-forge]( https://conda-forge.org/ ) to build wheels alongside conda packages. These would upload to [Anaconda.org]( https://anaconda.org ), but could be installed [the same way one would with any third party `pip` repository]( https://packaging.python.org/guides/hosting-your-own-index/#hosting-your-own-simple-repository ). Alternatively PyPI package maintainers could manually copy over these wheels to PyPI.

This could use some feedback from the community. Namely is it useful? How do we solve any remaining issues with this strategy? Other comments? Some discussion with links to a few experiments and things to work out in issue ( https://github.com/conda-forge/conda-smithy/issues/608 ).
