### ISSUE TITLE
"overhanging" blocks

### ISSUE THREAD

**Issue by d-v-b** [constantinpape/z5#141] opened 2019-10-17 15:01 UTC
When creating `n5` arrays with `zarr` using a chunksize that doesn't evenly divide the dimensions of the array, `z5py` does not reconstruct the array properly:

(in `ipython`)
```python
In [7]: arr = zarr.open(store=zarr.N5Store('test.n5'), path='test', shape=(4,4), chunks=(3,3), compressor=numcodecs.GZip(level=-1)); arr[:] = 100; arr[:]                  
Out[7]: 
array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [8]: z5py.File('test.n5')['test'][:]                                                                                                                                    
Out[8]: 
array([[100., 100., 100., 100.],
       [100., 100., 100.,   0.],
       [100., 100., 100.,   0.],
       [100., 100., 100., 100.]])
```

**Comment by constantinpape** [comment] 2019-10-18 07:48
Yes, zarr-n5 does not clip overhanging chunks like java-n5 (and z5) does.
That's why this issue occurs. I am aware of this, however I am not sure what's the best way
of tackling this, because there are some other issues caused by this difference, e.g.
I don't think it's possible to read n5 files with clipped chunks in zarr.

**Comment by constantinpape** [comment] 2021-04-30 19:39
These issues are all fixed now and well tested in https://github.com/zarr-developers/zarr_implementations.

**Closed by constantinpape** 2021-04-30 19:39 UTC
